# Generated by Django 5.1.4 on 2025-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_category_name_alter_checklistitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('start', 'Start'), ('transfer', 'Transfer')], max_length=100),
        ),
       
    ]
