# Generated by Django 5.1.4 on 2025-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_checklistitem_verified_alter_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(default='Enter Name', max_length=200),
        ),
    ]
